# Copyright Â© 2024 Fabian H. Schneider

# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

name: â˜ï¸ðŸ§ pre-commit

on:
  push:
  workflow_dispatch:

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for auto-commit
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip3.12 install pre-commit

      - uses: actions/checkout@v4.1.7

      - name: Run pre-commit on all files
        id: pre-commit
        run: |
          pre-commit run --all-files | tee msg.txt || echo "status=$?" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Run pre-commit
          branch: ${{ github.ref }}

      - name: pre-commit result
        run: |
          cat msg.txt
          exit ${{ steps.pre-commit.outputs.status }}
